spring:
  data:
    mongodb:
      #uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb/${MONGO_DATABASE}
      uri: mongodb://adminuser=:admintestpass=@mongodb/mongodb
      repositories:
        enabled: true
