server:
  port: 8082

spring:
  application:
    name: customer-service
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongo
      repositories:
        enabled: true
